###############################################################################
#
###############################################################################
AWSTemplateFormatVersion: '2010-09-09'
Description: Example CI/CD CodePipeline
Parameters:
  artifactsBucket:
    Type: String
  theSourceRepo:
    Type: String
  theSourceBranch:
    Type: String
  pipelineName:
    Type: String
  theBuilderImage:
    Type: String
  theDeployerImage:
    Type: String

Resources:
  ##############################################################################
  #
  ##############################################################################
  wheelProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: example-wheel-build
      Description: Build and publish the Example wheel
      ServiceRole:
        Fn::ImportValue: exampleDeployRoleArnV1
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image:
          Ref: theBuilderImage
        EnvironmentVariables:
          - Name: mode
            Value: build_wheel
          - Name: region
            Value: us-east-1
          - Name: image_name
            Value: example-server
      Source:
        BuildSpec: deployment/buildspec.yml
        Type: CODEPIPELINE
      TimeoutInMinutes: 60

  ##############################################################################
  #
  ##############################################################################
  thePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name:
        Ref: pipelineName
      RoleArn:
        Fn::ImportValue: exampleDeployRoleArnV1
      ArtifactStore:
        Type: S3
        Location:
          Ref: artifactsBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              RunOrder: 1
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: '1'
              Configuration:
                RepositoryName:
                  Ref: theSourceRepo
                BranchName:
                  Ref: theSourceBranch
              OutputArtifacts:
                - Name: theSources

        - Name: BuildPublish
          Actions:
            - Name: BuildPublishWheel
              RunOrder: 1
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName:
                  Ref: wheelProject
              InputArtifacts:
                - Name: theSources
              OutputArtifacts:
                - Name: wheelOutput
