###############################################################################
#
###############################################################################
AWSTemplateFormatVersion: '2010-09-09'
Description: Mantis CI/CD CodePipeline
Parameters:
  artifactsBucket:
    Type: String
  buildSecurityGroup:
    Type: String
  theSourceRepo:
    Type: String
  theSourceBranch:
    Type: String
  pipelineName:
    Type: String
  buildRole:
    Type: String
  pipelineRole:
    Type: String
  sandboxRole:
    Type: String
  theBuilderImage:
    Type: String
  theDeployerImage:
    Type: String

Resources:
  ##############################################################################
  #
  ##############################################################################
  wheelProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: example-wheel-build
      Description: Build and publish the Mantis wheel
      ServiceRole:
        Ref: buildRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image:
          Ref: theBuilderImage
        EnvironmentVariables:
          - Name: mode
            Value: build_wheel
          - Name: image_name
            Value: mantis-analysis-server
          - Name: module_name
            Value: mantis2
          - Name: account_id
            Value: 118820389895
      Source:
        BuildSpec: code_pipeline/buildspec.yml
        Type: CODEPIPELINE
      TimeoutInMinutes: 60
      VpcConfig:
        VpcId:
          Fn::ImportValue: VPCIdV1
        Subnets:
          - Fn::ImportValue: PrivateSubnetOneV1
          - Fn::ImportValue: PrivateSubnetTwoV1
          - Fn::ImportValue: PrivateSubnetThreeV1
          - Fn::ImportValue: PrivateSubnetFourV1
        SecurityGroupIds:
          - Ref: buildSecurityGroup

  ##############################################################################
  #
  ##############################################################################
  imageProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: mantis-image-build
      Description: Build and publish the Mantis docker image
      ServiceRole:
        Ref: buildRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image:
          Ref: theDeployerImage
        EnvironmentVariables:
          - Name: mode
            Value: build_image
          - Name: image_name
            Value: mantis-analysis-server
          - Name: module_name
            Value: mantis2
          - Name: account_id
            Value: 118820389895
      Source:
        BuildSpec: code_pipeline/buildspec.yml
        Type: CODEPIPELINE
      TimeoutInMinutes: 60
      VpcConfig:
        VpcId:
          Fn::ImportValue: VPCIdV1
        Subnets:
          - Fn::ImportValue: PrivateSubnetOneV1
          - Fn::ImportValue: PrivateSubnetTwoV1
          - Fn::ImportValue: PrivateSubnetThreeV1
          - Fn::ImportValue: PrivateSubnetFourV1
        SecurityGroupIds:
          - Ref: buildSecurityGroup


  ##############################################################################
  #
  ##############################################################################
  sandboxDeploy:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: mantisSandboxDeploy
      Description: Deploy the Mantis Docker image to ECS/Fargate
      ServiceRole:
        Ref: buildRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:1.12.1
        EnvironmentVariables:
          - Name: mode
            Value: deploy_fargate
          - Name: module_name
            Value: mantis2
          - Name: build_role
            Value:
              Ref: sandboxRole
          - Name: target_env
            Value: sb
      Source:
        BuildSpec: code_pipeline/buildspec.yml
        Type: CODEPIPELINE
      TimeoutInMinutes: 60
      Tags:
        - Key: ProjCode
          Value: Mantis

  ##############################################################################
  #
  ##############################################################################
  thePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name:
        Ref: pipelineName
      RoleArn:
        Ref: pipelineRole
      ArtifactStore:
        Type: S3
        Location:
          Ref: artifactsBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              RunOrder: 1
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: '1'
              Configuration:
                RepositoryName:
                  Ref: theSourceRepo
                BranchName:
                  Ref: theSourceBranch
              OutputArtifacts:
                - Name: theSources

        - Name: BuildPublish
          Actions:
            - Name: BuildPublishWheel
              RunOrder: 1
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName:
                  Ref: wheelProject
              InputArtifacts:
                - Name: theSources
              OutputArtifacts:
                - Name: wheelOutput
            - Name: BuildPublishImage
              RunOrder: 2
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName:
                  Ref: imageProject
              InputArtifacts:
                - Name: theSources
              OutputArtifacts:
                - Name: imageOutput

        - Name: DeploySandbox
          Actions:
            - Name: BuildAction
              RunOrder: 1
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName:
                  Ref: sandboxDeploy
              InputArtifacts:
                - Name: theSources
              OutputArtifacts:
                - Name: deploySandboxOutput
